import {
  autoGeneratedHashKey,
  table,
  attribute,
} from '@aws/dynamodb-data-mapper-annotations'
import { mapper, BaseModel } from '@360mediadirect/modeler'
import { Organization } from '../../../../common/interfaces/Organization'
import { AttributePath, FunctionExpression } from '@aws/dynamodb-expressions'
import { QueryOptions } from '@aws/dynamodb-data-mapper'
import { Schema } from '@aws/dynamodb-data-marshaller'

export const ddbSchemaOrg: Schema = {
  id: { type: 'String' },
  createdAt: { type: 'Number' },
  updatedAt: { type: 'Number' },
  deletedAt: { type: 'Number' },
  deletedReason: { type: 'String' },
  name: { type: 'String' },
  domainScopes: { type: 'Any' },
  type: { type: 'String' },
  seedUserIds: { type: 'List', memberType: { type: 'String' } },
}

@table(process.env.ORGANIZATION_TABLE_NAME)
export class OrganizationModel extends BaseModel implements Organization {
  @autoGeneratedHashKey() id: string
  @attribute() name: string
  @attribute() domainScopes?: Record<string, string[]>
  @attribute({ defaultProvider: () => Date.now() })
  createdAt: number
  @attribute({ defaultProvider: () => Date.now() })
  updatedAt: number
  @attribute() deletedAt: number

  /**
   * Gets an array of active orgs in arbitrary order. "Active" is defined as
   * not having a truthy deletedAt value.
   * @param limit The number os records to retrieve
   * @param startKey The last org ID returned from the last set of results.
   *    This instructs this function to retrieve records starting from that
   *    key, exclusive of that record itself.
   * @returns An array of active orgs
   */
  public static async getActiveOrganizations(
    limit: number,
    startKey?: Record<string, any>,
  ) {
    const orgs = []
    const options: QueryOptions = {
      limit,
      filter: new FunctionExpression(
        'attribute_not_exists',
        new AttributePath('deletedAt'),
      ),
      ...(startKey && { startKey }),
    }
    for await (const org of mapper.scan(OrganizationModel, options)) {
      orgs.push(org)
    }
    return orgs
  }
}
